import numpy as np
import os

# Load the data generated by your bitnet.py script
inputs = np.loadtxt("./Vitis_HLS/src/tb_data/tb_input_features.dat")
golden = np.loadtxt("./Vitis_HLS/src/tb_data/tb_output_predictions.dat")

num_samples = inputs.shape[0]

# Define the output directory and filename on separate variables
output_dir = "./Vitis/src/tb_data"
output_filename = "test_data.h"

# Safely combine them for the final file path
output_path = os.path.join(output_dir, output_filename)

# Create the target directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

with open(output_path, "w") as f:
    f.write("#ifndef TEST_DATA_H\n#define TEST_DATA_H\n\n")
    f.write(f"#define NUM_SAMPLES {num_samples}\n\n")
    
    # 1. Write Input Features
    f.write("static const float tb_inputs[NUM_SAMPLES][64] = {\n")
    for row in inputs:
        f.write("    {" + ", ".join(f"{val}f" for val in row) + "},\n")
    f.write("};\n\n")
    
    # 2. Write Golden Output Predictions
    f.write("static const float tb_golden[NUM_SAMPLES][64] = {\n")
    for row in golden:
        f.write("    {" + ", ".join(f"{val}f" for val in row) + "},\n")
    f.write("};\n\n")
    
    f.write("#endif // TEST_DATA_H\n")

print(f"[Success] Created {output_filename} at {output_dir}!")